/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Dialogc_buttonListener */

#ifndef _Included_Dialogc_buttonListener
#define _Included_Dialogc_buttonListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
