/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Dialogc_textListener */

#ifndef _Included_Dialogc_textListener
#define _Included_Dialogc_textListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
